project:
  type: website

website:
  title: "Chao Liang"
  navbar:
    logo: "images/logo.png"
    background: none
    search: true
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: work.qmd
        text: Work
      - href: blog.qmd
        text: Blog
  page-footer:
    left: "© 2025 Chao Liang. All rights reserved."
    right:
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com/

format:
  html:
    theme:
      light: [litera, custom.scss]
      dark: [darkly, custom-dark.scss]
    css: styles.css
    toc: true
    page-layout: full
    mainfont: "Inter, system-ui, -apple-system, sans-serif"
    monofont: "JetBrains Mono, monospace"
    smooth-scroll: true
    code-copy: true
    code-overflow: wrap
    highlight-style: github
